# # TODO: add papers by configuration file
# base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
# user_name: "Ferry1231"
# repo_name: "arxiv-daily"
# show_authors: True
# show_links: True
# show_badge: True
# max_results: 10

# publish_readme: True
# publish_gitpage: True
# publish_wechat: False

# # file paths
# json_readme_path: './docs/cv-arxiv-daily.json'
# json_gitpage_path: './docs/cv-arxiv-daily-web.json'
# json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

# md_readme_path: 'README.md'
# md_gitpage_path: './docs/index.md'
# md_wechat_path: './docs/wechat.md'

# # keywords to search
# keywords:
#     "SLAM": 
#         filters: ["SLAM", "Visual Odometry"]
#     "SFM":
#         filters: ["SFM", "Structure from Motion"]
#     "Visual Localization":
#         filters: ["Visual Localization","Camera Localization",
#                   "Camera Re-localisation","Loop Closure Detection",
#                   "visual place recognition","image retrieval"]
#     "Keypoint Detection":
#         filters: ["Keypoint Detection", "Feature Descriptor"]
#     "Image Matching":
#         filters: ["Image Matching", "Keypoint Matching", 
#                   "Line Segment Detection", "Local Feature Matching"]
#     "NeRF":
#         filters: ["NeRF"]


base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
max_results: 15
user_name: "Ferry1231"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True


categories:
  diffusion:
    query: "diffusion model OR generative model"
    output_dir: "/github/workspace/diffusion"
  agent:
    query: "AI agent OR multi-agent system"
    output_dir: "/github/workspace/agent"
  ml_theory:
    query: "deep learning theory OR neural tangent kernel"
    output_dir: "/github/workspace/ml-theory"
  stat_ml:
    query: "cat:stat.ML"
    output_dir: "/github/workspace/stat-ml"

output_templates:
  json_name: "papers.json"
  md_name: "README.md"
